// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sstiikeqynckefjsumyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdGlpa2VxeW5ja2VmanN1bXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTkzMjUsImV4cCI6MjA3MTM3NTMyNX0.IjnUBdCNS399S3YLtbV0xcdXRPacQj1_gs6xVKhECjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});